apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../sources
  - cm-flux-prometheus.yaml
  - ../prometheus
  - ./statsd
  - ../statsd
  - cm-flux-eagle.yaml
  - ../kube-eagle

#configMapGenerator:
#  - name: flux-rucio-server
#    files:
#      - values.yaml=flux-rucio-server.yaml
#configurations:
#  - kustomizeconfig.yaml
