apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rucio
resources:
  - rucio-traceserver-helm.yaml
configMapGenerator:
  - name: cms-rucio-traceserver
    files:
      - values.yaml=cms-rucio-traceserver.yaml
configurations:
  - kustomizeconfig.yaml
