apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rucio
resources:
  - cms-grid-cvmfs-helm.yaml
configMapGenerator:
  - name: cms-grid-cvmfs
    files:
      - values.yaml=cms-grid-cvmfs.yaml
configurations:
  - kustomizeconfig.yaml
