apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rucio
configMapGenerator:
  - name: cms-rucio-server
    files:
      - values.yaml=cms-rucio-server.yaml
configurations:
  - kustomizeconfig.yaml
