apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rucio-server
spec:
  releaseName: server-flux
  chart:
    spec:
      chart: rucio-server
      sourceRef:
        kind: HelmRepository
        name: rucio
        namespace: flux-system
#      chart: ./charts/rucio-server
#      sourceRef:
#        kind: GitRepository
#        name: rucio-git
#        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: cms-rucio-common-server
    - kind: ConfigMap
      name: cms-rucio-server
    - kind: ConfigMap
      name: flux-rucio-server
    - kind: ConfigMap
      name: flux-release-server
    - kind: Secret
      name: rucio-secrets
      valuesKey: db_string
      targetPath: config.database.default

# FIXME: Can we produce a common "cms-rucio-common" and "flux-release"