apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cms-tier2-consistency
spec:
  releaseName: tier2-consistency
  chart:
    spec:
      chart: helm/rucio-consistency
      version: 3.2.0
      sourceRef:
        kind: HelmRepository
        name: cms-rucio-oci
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: cms-consistency
    - kind: ConfigMap
      name: instance-consistency
    - kind: ConfigMap
      name: instance-consistency-tier2-jobs
