apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rucio
resources:
  - cms-consistency-helm.yaml
  - cms-consistency-tier2-helm.yaml
configMapGenerator:
  - name: cms-consistency
    files:
      - values.yaml=cms-consistency.yaml
configurations:
  - kustomizeconfig.yaml
