apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rucio
resources:
  - rucio-authserver-helm.yaml
configMapGenerator:
  - name: cms-rucio-authserver
    files:
      - values.yaml=cms-rucio-authserver.yaml
configurations:
  - kustomizeconfig.yaml
