apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rucio
resources:
  - rucio-webui-helm.yaml
configMapGenerator:
  - name: cms-rucio-webui
    files:
      - values.yaml=cms-rucio-webui.yaml
  - name: instance-rucio-release-patch
    files:
      - values.yaml=ui-release-patch.yaml
configurations:
  - kustomizeconfig.yaml
