#reaper2Count: 4
#judgeInjectorCount: 3
#judgeRepairerCount: 2
#conveyorPollerCount: 2
#conveyorFinisherCount: 4
#judgeEvaluatorCount: 8

# Temporary until we can turn on the real daemons

abacusAccountCount: 0
abacusRseCount: 0
conveyorStagerCount: 0
hermesCount: 0
judgeCleanerCount: 0
judgeEvaluatorCount: 0
judgeInjectorCount: 0
judgeRepairerCount: 0
tracerKronosCount: 0
transmogrifierCount: 0
undertakerCount: 0
darkReaperCount: 0
reaperCount: 0
reaper2Count: 0
minosCount: 0
necromancerCount: 0
conveyorTransferSubmitterCount: 0
conveyorPreparerCount: 0
conveyorPollerCount: 0
conveyorFinisherCount: 0

# Should be one in normal running


darkReaper:
  includeRses: "reaper=True"

reaper2:
  includeRses: "reaper=True"
  threads: 8
  greedy: 0
  sleepTime: 15

conveyorTransferSubmitter:
  threads: 5

conveyorPoller:
  threads: 5
  resources: 
    limits:
      cpu: 2000m
      memory: 1000Mi
    requests:
      cpu: 750m
      memory: 400Mi

judgeEvaluator:
  threads: 8
  # Can try this in 1.26
  # didLimit: 1000
  resources:
    limits:
      memory: 1000Mi
    requests:
      memory: 200Mi

judgeRepairer:
  threads: 2
judgeInjector:
  threads: 3

conveyorFinisher: 
  threads: 5
  resources:
    limits:
      memory: 1000Mi
    requests:
      memory: 400Mi

podLabels:
  rucioInstance: "prod"

transmogrifier:
  threads: 4
  sleepTime: 30


config:
    common:
        loglevel: "INFO"
#        loglevel: "DEBUG"

