consistency:
  ignore:
     - /store/backfill
     - /store/test
     - /store/unmerged
     - /store/temp
     - /store/mc/SAM
     - /store/mc/HC
     - /store/accounting
     - /store/express/tier0_harvest
  sites:
    T1_DE_KIT_Disk:
      interval: 7
      server: cmsxrootd-kit.gridka.de:1094
      server_root: /
      timeout: 3600
    T1_ES_PIC_Disk:
      interval: 7
      server: xrootd-cmst1-door.pic.es
    T1_UK_RAL_Tape:
      interval: 0
      maxdarkfraction: "0.0000001"
    T1_US_FNAL_Disk:
      interval: 7
      server: cmsdcadisk.fnal.gov
      server_root: /dcache/uscmsdisk
      maxdarkfraction: 0.05
      maxmissfraction: 0.02
    T1_IT_CNAF_Disk:
      server: xrootd-cms.cr.cnaf.infn.it
      interval: 7
    T0_CH_CERN_Disk:
      server: eoscms.cern.ch
      server_root: /eos/cms/tier0
      interval: 7
    T1_FR_CCIN2P3_Tape:
      server: ccxrootdcms.in2p3.fr:1094
      server_root: /pnfs/in2p3.fr/data/cms/data
      interval: 7
    T1_FR_CCIN2P3_Disk:
      server: ccxrootdcms.in2p3.fr:1094
      server_root: /pnfs/in2p3.fr/data/cms/disk/data
      interval: 7
    T1_RU_JINR_Disk:
      server: xrootd01.jinr-t1.ru:1094
      server_root: /pnfs/jinr-t1.ru/data/cms
      interval: 7
