reaperCount: 4
judgeInjectorCount: 3
judgeRepairerCount: 2
conveyorPollerCount: 2
conveyorFinisherCount: 4
judgeEvaluatorCount: 8

darkReaper:
  includeRses: "reaper=True"

reaper:
  includeRses: "reaper=True"
  sleepTime: 15

conveyorTransferSubmitter:
  threads: 5

conveyorPoller:
  threads: 5
  resources: 
    limits:
      cpu: 2000m
      memory: 1000Mi
    requests:
      cpu: 750m
      memory: 400Mi

judgeEvaluator:
  threads: 8
  didLimit: 1000
  resources:
    limits:
      memory: 1000Mi
    requests:
      memory: 200Mi

judgeRepairer:
  threads: 2
judgeInjector:
  threads: 3

conveyorFinisher: 
  threads: 5
  resources:
    limits:
      memory: 1000Mi
    requests:
      memory: 400Mi

podLabels:
  rucioInstance: "prod"

transmogrifier:
  threads: 4
  sleepTime: 30

tracerKronos:
  # FIXME: Was 5 before 1.24 problems with Kronos (around still dropping connections)
  threads: 2


config:
    common:
        loglevel: "INFO"
#        loglevel: "DEBUG"

    tracer_kronos:
        # FIXME: Both used to be 50 before 1.24 problems with Kronos
        chunksize: "50"
        prefetch_size: "50"
