reaperCount: 4
judgeInjectorCount: 2
judgeRepairerCount: 2
conveyorPollerCount: 2
conveyorFinisherCount: 4
judgeEvaluatorCount: 2
tracerKronosCount: 3

darkReaper:
  includeRses: "reaper=True"

reaper:
  includeRses: "reaper=True"
  threads: 8
  chunkSize: 1000
  sleepTime: 30

conveyorTransferSubmitter:
  threads: 5

conveyorPoller:
  threads: 5
  resources: 
    limits:
      cpu: 2000m
      memory: 1000Mi
    requests:
      cpu: 750m
      memory: 400Mi

judgeEvaluator:
  threads: 8
  didLimit: 1000
  resources:
    limits:
      memory: 1000Mi
    requests:
      memory: 200Mi

judgeRepairer:
  threads: 2
judgeInjector:
  threads: 3

conveyorFinisher: 
  threads: 5
  resources:
    limits:
      memory: 1000Mi
    requests:
      memory: 400Mi

podLabels:
  rucioInstance: "prod"

transmogrifier:
  threads: 4
  sleepTime: 30

tracerKronos:
  threads: 5
  sleepTimeFiles: 10
  sleepTimeDatasets: 30

config:
    common:
        loglevel: "INFO"

