replicaCount: 3
authReplicaCount: 2
ingress:
  hosts: 
    - cms-rucio.cern.ch
authIngress:
  hosts: 
    - cms-rucio-auth.cern.ch
traceIngress:
  hosts: 
    - cms-rucio-trace.cern.ch

config:
  oidc:
    idpsecrets: "/opt/rucio/etc/idpsecrets.json"
    admin_issuer: "cms"
    expected_audience: "rucio"

secretMounts:
  - secretName: idpsecrets
    mountPath: /opt/rucio/etc/
    subPaths:
      - idpsecrets.json
# Check the above in 1.31. Should be same as below. Probably goes into auth file
#additionalSecrets:
#  idpsecrets:
#    secretName: idpsecrets
#    mountPath: /opt/rucio/etc/
#    subPaths:
#      - idpsecrets.json
