replicaCount: 3
authReplicaCount: 2
ingress:
  hosts: 
    - cms-rucio.cern.ch
authIngress:
  hosts: 
    - cms-rucio-auth.cern.ch
traceIngress:
  hosts: 
    - cms-rucio-trace.cern.ch

config:
  oidc:
    idpsecrets: "/opt/rucio/etc/idpsecrets.json"
    admin_issuer: "cms"
    expected_audience: "rucio"

additionalSecrets:
  idpsecrets:
    secretName: idpsecrets
    mountPath: /opt/rucio/etc/
    subPaths:
      - idpsecrets.json