apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rucio
configMapGenerator:
  - name: cms-traces
    files:
      - values.yaml=cms-traces.yaml
configurations:
  - kustomizeconfig.yaml
