apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rucio-cronjobs
spec:
  releaseName: cronjobs-flux
  chart:
    spec:
      chart: rucio-cron-jobs
      sourceRef:
        kind: HelmRepository
        name: cms-kubernetes
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: flux-cronjobs
