apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rucio
resources:
  - ../base
  - ../base/rucio-daemons
  - ../base/rucio-server
  - ../base/rucio-webui
  - ../base/cms-rucio-consistency
  - rucio-daemons-helm.yaml
  - rucio-server-helm.yaml
  - rucio-webui-helm.yaml
  - cms-rucio-consistency.yaml
configMapGenerator:
  - name: flux-rucio-server
    files:
      - values.yaml=flux-rucio-server.yaml
  - name: flux-rucio-daemons
    files:
      - values.yaml=flux-rucio-daemons.yaml
  - name: flux-rucio-webui
    files:
      - values.yaml=flux-rucio-webui.yaml
  - name: flux-release
    files:
      - values.yaml=flux-release.yaml
  - name: flux-consistency
    files:
      - values.yaml=flux-consistency.yaml
  - name: flux-consistency-jobs
    files:
      - values.yaml=flux-consistency-jobs.yaml
configurations:
  - kustomizeconfig.yaml
