apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rucio-probes
spec:
  releaseName: probes-flux
  chart:
    spec:
      chart: rucio-probes
      sourceRef:
        kind: HelmRepository
        name: rucio
        namespace: flux-system
#      chart: ./charts/rucio-daemons
#      sourceRef:
#        kind: GitRepository
#        name: rucio-git
#        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: cms-rucio-common
    - kind: ConfigMap
      name: cms-rucio-probes
    - kind: ConfigMap
      name: flux-rucio-probes
    - kind: ConfigMap
      name: flux-release
    - kind: Secret
      name: rucio-secrets
      valuesKey: db_string
      targetPath: config.database.default
