apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rucio-ui
spec:
  releaseName: ui-flux
  chart:
    spec:
      chart: rucio-ui
      sourceRef:
        kind: HelmRepository
        name: rucio
        namespace: flux-system
#      chart: ./charts/rucio-server
#      sourceRef:
#        kind: GitRepository
#        name: rucio-git
#        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: cms-rucio-common
    - kind: ConfigMap
      name: cms-rucio-webui
    - kind: ConfigMap
      name: flux-rucio-webui
    - kind: ConfigMap
      name: flux-release
    - kind: Secret
      name: rucio-secrets
      valuesKey: db_string
      targetPath: config.database.default
