apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rucio
resources:
  - namespace.yaml
configMapGenerator:
  - name: cms-rucio-common
    files:
      - values.yaml=cms-rucio-common.yaml
configurations:
  - kustomizeconfig.yaml
