apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rucio
resources:
  - rucio-daemons-helm.yaml
configMapGenerator:
  - name: cms-rucio-daemons
    files:
      - values.yaml=cms-rucio-daemons.yaml
configurations:
  - kustomizeconfig.yaml
