apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cms-rucio-cron
spec:
  releaseName: rucio-cron
  chart:
    spec:
      chart: rucio-cron-jobs
      version: 0.6.0
      sourceRef:
        kind: HelmRepository
        name: cms-rucio
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: cms-cron
    - kind: ConfigMap
      name: instance-rucio-cron
